### ISSUE TITLE
小姐姐，你需要适配一下低分辨率屏幕 ![手动狗头]

### ISSUE THREAD

**Issue by mxy493** [xujiangjiang/Easy-Bug-Manager#3]

**Comment by mxy493** [comment]
对八起，我是憨憨，撸bug去了🤐

**Comment by WhistleB1ower** [comment]
这个是Easybug吗？



在 2020-09-29 08:55:52，"mxy493" <notifications@github.com> 写道：

我这1920 × 1080的都扛不住~

**Comment by mxy493** [comment]
> 这个是Easybug吗？ 在 2020-09-29 08:55:52，"mxy493" <notifications@github.com> 写道： 我这1920 × 1080的都扛不住~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不是😅
没问题的，拖边框就能调整大小了~
